# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - develop
      - release

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '16.3.0'

    - name: Build Web Pages
      run: npm install && npm build

#    - name: Deploy to Staging server
#      uses: easingthemes/ssh-deploy@main
#      env:
#        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
#        ARGS: "-rltgoDzvO"
#        SOURCE: "quick-web-admin/dist/"
#        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#        REMOTE_USER: ${{ secrets.REMOTE_USER }}
#        TARGET: ${{ secrets.REMOTE_TARGET }}
#        EXCLUDE: "/dist/, /node_modules/"